export const ADD_USER = 'ADD_USER'
export const SET_PLACE = 'SET_PLACE'
export const GET_PLACE = 'GET_PLACE'
export const REMOVE_PLACE = 'REMOVE_PLACE'

export const ADD_IMAGE = 'ADD_IMAGE'
export const DELETE_IMAGE = 'DELETE_IMAGE'
export const ADD_LOCATION = 'ADD_LOCATION'
export const DELETE_LOCATION = 'DELETE_LOCATION'
export const ADD_PLACE_NAME = 'ADD_PLACE_NAME'
export const DELETE_PLACE_NAME = 'DELETE_PLACE_NAME'

export const UI_START_LOADING = "UI_START_LOADING"
export const UI_STOP_LOADING = "UI_STOP_LOADING" 

export const EMAIL_CONFIRMED = "EMAIL_CONFIRMED" 
export const EMAIL_NOT_CONFIRMED = "EMAIL_NOT_CONFIRMED" 

export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL" 
// export const EMAIL_NOT_CONFIRMED = "EMAIL_NOT_CONFIRMED" 

export const PASSWORD_CONFIRMED = "PASSWORD_CONFIRMED" 

export const REMOVE_ID_TOKEN = "REMOVE_ID_TOKEN" 

export const USER_LOGIN = "USER_LOGIN" 

